package io.github.edadma.kutter

import java.io.{File, PrintWriter}
import scala.io.Source
import zio.json.*

// The project model — kutter's source of truth, and what a `.kutter` file on disk holds. It is a
// plain data model, deliberately above MLT: `Player.buildGraph` compiles it into a tractor to play
// or export, but the project itself knows nothing of transitions or playlists. That separation is
// what lets a project be created in the UI, generated by a batch script, saved as JSON, and reopened,
// while the graph it compiles to stays an implementation detail.
//
// The model is a fixed-track NLE, like kdenlive: media is *imported into a bin*, then *placed onto
// tracks*. A track is a container — V1, V2 for video (composited top-down) and A1, A2 for audio
// (mixed) — that always exists whether or not it holds anything, and sequences a list of placed clips
// along the timeline. Importing a clip is not the same as putting it on the timeline; a bin clip can
// be placed on several tracks, or several times on one track, each placement its own in/out window.
//
// A lower third is split into the things that were conflated when it was hardcoded: its **content**
// (the words), its **style** (the look, chosen from a set of reusable presets rather than baked into
// the renderer), and — like any other clip — its **placement** on the timeline. A lower third lives in
// the project as reusable content (a title library); it is put on screen by placing it on a video track
// (a `PlacedClip` carrying its `titleId`), where it composites over the tracks below and fades in and
// out over its placement's window. Automated typeset lower thirds are kutter's reason for being.

/** A colour, components in 0..1 — the wire form styles are written in. */
final case class Rgba(r: Double, g: Double, b: Double, a: Double = 1.0)

object Rgba:
  given JsonCodec[Rgba] = DeriveJsonCodec.gen

/** Where a lower third sits along the bottom of the frame; sets the bar's horizontal placement and
  * how its text is aligned within it. */
enum Anchor:
  case LowerLeft, LowerCenter, LowerRight

object Anchor:
  given JsonCodec[Anchor] = DeriveJsonCodec.gen

/** The look of a lower third, independent of its words — a reusable preset the card renderer draws
  * from. A style with a fully transparent `bar` draws no bar (the `shadow` then keeps the text
  * legible over bright footage); `stripe` is the accent edge, absent when `None`.
  *
  * When `texish` is set, the card is typeset from that texish document instead of drawn by the
  * hand-rolled Cairo renderer — the look then lives entirely in the template, and the bar/stripe/colour
  * fields above are ignored. The template reads the overlay's words from the `ltname` and `lttitle`
  * variables (`\the\ltname`, `\the\lttitle`), so one template dresses a whole batch of lower thirds. */
final case class Style(
    id:           String,
    label:        String,
    bar:          Rgba,
    stripe:       Option[Rgba],
    cornerRadius: Double, // as a fraction of the bar's height
    nameColor:    Rgba,
    titleColor:   Rgba,
    nameBold:     Boolean,
    shadow:       Boolean,
    anchor:       Anchor,
    widthFrac:    Double,          // bar width as a fraction of the frame width
    heightFrac:   Double,          // bar height as a fraction of the frame height
    texish:       Option[String] = None, // when set, the card is typeset from this texish document
)

object Style:
  given JsonCodec[Style] = DeriveJsonCodec.gen

  /** The dark translucent bar with a blue accent stripe and a bold name — the broadcast default. */
  val broadcastBlue = Style(
    "broadcast-blue", "Broadcast Blue",
    bar = Rgba(0.05, 0.06, 0.08, 0.72),
    stripe = Some(Rgba(0.29, 0.60, 0.96, 1.0)),
    cornerRadius = 0.12,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.82, 0.86, 0.92, 1),
    nameBold = true,
    shadow = false,
    anchor = Anchor.LowerLeft,
    widthFrac = 0.60,
    heightFrac = 0.18,
  )

  /** A wide solid accent-coloured bar, centred, with white text — a bolder look. */
  val boldBar = Style(
    "bold-bar", "Bold Bar",
    bar = Rgba(0.29, 0.60, 0.96, 0.92),
    stripe = None,
    cornerRadius = 0.06,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.90, 0.94, 1.0, 1),
    nameBold = true,
    shadow = false,
    anchor = Anchor.LowerCenter,
    widthFrac = 0.72,
    heightFrac = 0.16,
  )

  /** No bar at all — white text over a soft shadow, for a clean unobtrusive credit. */
  val minimal = Style(
    "minimal", "Minimal",
    bar = Rgba(0, 0, 0, 0),
    stripe = None,
    cornerRadius = 0.0,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.86, 0.89, 0.94, 1),
    nameBold = true,
    shadow = true,
    anchor = Anchor.LowerLeft,
    widthFrac = 0.60,
    heightFrac = 0.18,
  )

  /** A texish-typeset card: the name a bold EB Garamond heading over the title in normal weight, filling
    * the lower third of the frame over a translucent bar the footage shows through. The look is the
    * template, so this is also the worked example of a lower third expressed in texish — copy it into a
    * project and edit the document to taste. */
  val texishCard = minimal.copy(
    id = "texish-card",
    label = "Texish Card",
    texish = Some(texishCardTemplate),
  )

  /** The default card template — core primitives only, no `\use{document}`: everything it needs
    * (`\geometry`, `\pagecolor`, `\vfill`, `\colorbox`, `\parbox`, `\color`, `\font`, `\vskip`) is built
    * in, and the only thing the `document` package would add that a card touches is the page-number
    * footer, which a still overlay does not want anyway. This is texish's own `lowerthird-demo` adapted to
    * kutter's data path: `\pagecolor{transparent}` leaves the page unpainted so the video shows through
    * everywhere the template does not draw; `\geometry margin:0` lets the panel span the whole frame; and
    * `\vfill` pushes it to the foot. The panel is a full-bleed **fixed-height** `\parbox` (1260×220pt,
    * content top-aligned) behind a translucent `\colorbox` (55% black, the footage showing through), with
    * `\fboxsep 10` adding 10px of padding on every side — 1260+20 wide and 220+20 tall — so the band is
    * exactly 1280×240, one third of the 720-tall frame, flush to the bottom, its text inset 10px. The name
    * and title (read from the `ltname`/`lttitle` variables) are set as flowing paragraphs — the name a bold
    * EB Garamond heading, the title normal weight below it, `\par`/`\vskip 14` apart. Numbers are in points
    * and the card is rendered at one pixel per point, so they read directly against a 1280×720 frame. */
  private def texishCardTemplate: String =
    """\geometry margin:0
      |\pagecolor{transparent}
      |\vfill
      |\set fboxsep {10}
      |\colorbox[0.55]{black}{\parbox[c][220pt][t]{1260pt}{
      |\color{white}
      |\set parindent {0}
      |\font ebgaramond 30 bold
      |\the\ltname
      |\par
      |\vskip 14
      |\font ebgaramond 28 regular
      |\the\lttitle
      |}}
      |""".stripMargin

  /** The styles a new project starts with. */
  val presets: List[Style] = List(broadcastBlue, boldBar, minimal, texishCard)

/** One lower third's reusable content: its words, how long it fades, and the style it wears. It carries
  * no timeline window — a lower third is placed on a video track like any clip (a [[PlacedClip]] with
  * this title's id), and that placement owns when it shows and for how long; the fade length here is
  * applied within whatever window the placement gives it.
  *
  * `body` is an escape hatch: a raw texish document for this one card, which overrides whatever the
  * style would have drawn (see `CardRenderer`). The words are still available to it as the `ltname` and
  * `lttitle` variables, so a body can read them or ignore them and set the card however it likes. With
  * no `body`, the card is drawn by the style — a texish template when the style has one, else the
  * hand-rolled Cairo look. */
final case class LowerThird(
    id:         String,
    name:       String,
    title:      String,
    fadeFrames: Int            = 12,
    styleId:    String         = "broadcast-blue",
    body:       Option[String] = None, // a raw texish document for just this card, overriding its style
    source:     Option[String] = None, // the .klt file this was imported from, so a re-import replaces it
)

object LowerThird:
  given JsonCodec[LowerThird] = DeriveJsonCodec.gen

/** Whether a media clip contributes a picture or a sound track. Video clips go on video tracks and are
  * composited top-down; audio clips go on audio tracks and are mixed. */
enum MediaKind:
  case Video, Audio

object MediaKind:
  given JsonCodec[MediaKind] = DeriveJsonCodec.gen

/** One piece of source media in the project's bin: an imported video or audio file. A bin clip is a
  * source, not a placement — it names a file that can be dropped onto a track (once, or several times)
  * with its own in/out window each time. `frames` is the source's length against the playback profile,
  * measured once at import — a trim needs it to know how far a placement can be extended (a placement's
  * window can grow up to the source's own length) and to map a trimmed block's filmstrip/waveform back
  * onto the whole source. It is 0 for a clip from a project saved before trimming existed; callers then
  * fall back to the placement's own end, so an old project still opens (just not extendable past what it
  * already shows). */
final case class MediaClip(id: String, path: String, kind: MediaKind, frames: Int = 0):
  /** The file's basename, for the bin and the clip label. */
  def name: String = path.split('/').lastOption.getOrElse(path)

object MediaClip:
  given JsonCodec[MediaClip] = DeriveJsonCodec.gen

  /** A new bin clip of `kind` for `path`, `frames` long against the profile, with a fresh id. */
  def make(path: String, kind: MediaKind, frames: Int = 0): MediaClip =
    MediaClip(s"clip-${System.nanoTime()}", path, kind, frames)

/** A source clip placed on a track: which bin clip it draws from (`clipId`), where it begins on the
  * timeline (`timelineStart`, in frames), and which slice of the source it plays (`inPoint` for
  * `length` frames). Several placements can reference the same bin clip; each carries its own window.
  *
  * `link` groups the two halves of a video-with-sound clip: the picture on a video track and its audio
  * on an audio track share a link id, so they read as one clip (the audio's peaks sit under the picture
  * for clapper/audio sync) and move together. Two independent clips have no link.
  *
  * `mc`/`angle` mark a placement as one *cut* of a multicam program: `mc` names the [[Multicam]] group
  * it belongs to and `angle` which of that group's synced angles it currently shows. A run of abutting
  * cuts on one video track is the switched program picture; the group's audio bed plays continuously from
  * a separate audio placement. When `angle` resolves to a title angle, the cut draws that angle's card
  * full-frame — a title cut is a video clip like any other (see `Player.buildGraph`), and `clipId` is
  * unused. An ordinary placement has `mc = None`.
  *
  * `titleId` marks a placement as a lower third put on a video track: it names the [[LowerThird]] whose
  * card the placement draws (full-frame, faded in and out over its window), and `clipId` is unused. This
  * is how a title reaches the screen — it composites over the tracks below through its transparent areas.
  * An ordinary placement has `titleId = None`. */
final case class PlacedClip(
    id:            String,
    clipId:        String,
    timelineStart: Int,
    inPoint:       Int,
    length:        Int,
    link:          Option[String] = None,
    mc:            Option[String] = None,
    angle:         Int            = 0,
    titleId:       Option[String] = None,
):
  /** The frame just past this placement's end on the timeline. */
  def timelineEnd: Int = timelineStart + length

object PlacedClip:
  given JsonCodec[PlacedClip] = DeriveJsonCodec.gen

  /** A placement of `clip` at `start`, playing the whole source for `length` frames from its head. */
  def make(clipId: String, start: Int, length: Int, inPoint: Int = 0, link: Option[String] = None): PlacedClip =
    PlacedClip(s"pc-${System.nanoTime()}", clipId, start, inPoint, length, link)

  /** A placement of the lower third `titleId` at `start`, drawing its card for `length` frames. A title
    * placement has no bin source (`clipId` empty) and plays from frame 0. */
  def makeTitle(titleId: String, start: Int, length: Int): PlacedClip =
    PlacedClip(s"pc-${System.nanoTime()}", "", start, 0, length, titleId = Some(titleId))

/** A track container: a named lane that always exists and sequences a list of placed clips along the
  * timeline. Video tracks are composited top-down (higher tracks over lower); audio tracks are mixed.
  * `volume` scales the track's sound (`muted` silences it outright), the per-track fader the mixer
  * drives. The clips are kept sorted by their timeline position when the graph is compiled. */
final case class Track(
    id:     String,
    name:   String,
    kind:   MediaKind,
    clips:  List[PlacedClip] = Nil,
    volume: Double           = 1.0,
    muted:  Boolean          = false,
):
  /** The clips in timeline order — the order the graph sequences them in. */
  def ordered: List[PlacedClip] = clips.sortBy(_.timelineStart)

  /** The frame just past the last clip on this track, or 0 when empty. */
  def contentEnd: Int = clips.map(_.timelineEnd).maxOption.getOrElse(0)

  /** The effective linear gain: 0 when muted, else the fader value. */
  def gain: Double = if muted then 0.0 else volume

  /** The track's number parsed from its name (V2 → 2, A3 → 3), or None for a name that isn't the
    * letter-plus-number form (a multicam lane). A video track and an audio track that share a number are a
    * pair — one camera's picture and its sound — so a standalone track takes the next free number rather
    * than one already claimed by a track of the other kind. */
  def num: Option[Int] = name.drop(1).toIntOption

object Track:
  given JsonCodec[Track] = DeriveJsonCodec.gen

/** The timeline's own video/audio format — the coordinate system the edit is authored against, not a
  * property of any one clip. `fps` (a rational, so the broadcast fractional rates are exact) is the
  * frame clock every timeline position is measured in: a clip's `timelineStart`, `length`, and
  * `inPoint`, and a lower third's window, are all counts of *these* frames, and MLT resolves each one
  * to the source frame nearest that instant, so a differently-rated clip is frame-rate-converted, never
  * indexed past its end. `width`/`height` is the compositing raster clips are scaled (conformed) into
  * and the lower-third cards are laid out against; `audioRate` is the rate the mix is resampled to.
  *
  * It is chosen once — auto-adopted from the first clip placed into a fresh project, or set explicitly
  * in project settings — and thereafter treated as fixed, because reinterpreting the existing frame
  * counts at a new `fps` would silently shift every edit in time. `width`/`height` and `audioRate`
  * are safe to change any time (a rescale and a resample, both non-destructive); only `fps` is load-
  * bearing once content exists. */
final case class TimelineSpec(
    width:     Int = 1280,
    height:    Int = 720,
    fpsNum:    Int = 30,
    fpsDen:    Int = 1,
    audioRate: Int = 48000,
):
  /** The frame rate as a single number — `fpsNum / fpsDen`. */
  def fps: Double = fpsNum.toDouble / math.max(1, fpsDen)

  /** A short human label for the settings surface, e.g. "1280×720 · 30 fps" or "· 23.98 fps". */
  def label: String =
    val r    = fps
    val rate = if math.abs(r - math.rint(r)) < 1e-6 then r.toInt.toString else f"$r%.2f"
    s"${width}×${height} · $rate fps"

object TimelineSpec:
  given JsonCodec[TimelineSpec] = DeriveJsonCodec.gen

  /** The default timeline format — 1280×720 at 30 fps, 48 kHz — what a project takes before any clip
    * sets it, and what a project saved before timeline specs existed loads as (the field's default
    * fills in for the missing JSON key). */
  val default: TimelineSpec = TimelineSpec()

  /** The exact rational for a frame rate, mapping the NTSC fractional rates to their /1001 form and
    * every other rate to a whole-number-over-one. Used when a rate is picked as a number (the settings
    * dropdown); auto-adopting a clip reads the source's own num/den directly and needs no guessing. */
  def fromFps(fps: Double, width: Int = 1280, height: Int = 720, audioRate: Int = 48000): TimelineSpec =
    val frac = fps - math.floor(fps)
    val (num, den) =
      if math.abs(frac - 0.97) < 0.02 || math.abs(frac - 0.976) < 0.02
      then ((math.round(fps) * 1000).toInt, 1001) // 23.976→24000/1001, 29.97→30000/1001, 59.94→60000/1001
      else (math.round(fps).toInt, 1)
    TimelineSpec(width, height, num, den, audioRate)

  /** The frame-rate choices the settings dropdown offers, as (label, num, den) — the common broadcast
    * and web rates, exact rationals. */
  val rateChoices: List[(String, Int, Int)] = List(
    ("23.976", 24000, 1001), ("24", 24, 1), ("25", 25, 1), ("29.97", 30000, 1001),
    ("30", 30, 1), ("50", 50, 1), ("59.94", 60000, 1001), ("60", 60, 1),
  )

  /** The resolution choices the settings dropdown offers, as (label, width, height). */
  val sizeChoices: List[(String, Int, Int)] = List(
    ("3840×2160 (4K UHD)", 3840, 2160), ("1920×1080 (1080p)", 1920, 1080),
    ("1280×720 (720p)", 1280, 720), ("854×480 (480p)", 854, 480), ("640×360 (360p)", 640, 360),
  )

  /** The audio-rate choices the settings dropdown offers, in Hz. */
  val audioRateChoices: List[Int] = List(48000, 44100)

/** A whole project: the bin of imported source media, the tracks the clips are sequenced on, the lower
  * thirds over the whole stack, the styles they draw from, the timeline format everything is authored
  * against, and the master output level. */
final case class Project(
    name:        String,
    bin:         List[MediaClip],
    tracks:      List[Track],
    lowerThirds: List[LowerThird],
    styles:      List[Style],
    master:      Double         = 1.0,
    spec:        TimelineSpec   = TimelineSpec.default,
    specLocked:  Boolean        = false, // true once the spec is set explicitly or content exists, so a later import stops auto-adopting
    created:     String         = "",    // the ISO date (YYYY-MM-DD) the project was started; blank for a project saved before this field existed
    multicams:   List[Multicam] = Nil,   // the multicam groups whose synced angles the program cuts draw from
):
  /** The video tracks, bottom-to-top — the compositing order (each composited over the ones below). */
  def videoTracks: List[Track] = tracks.filter(_.kind == MediaKind.Video)

  /** The audio tracks — each mixed into the output. */
  def audioTracks: List[Track] = tracks.filter(_.kind == MediaKind.Audio)

  /** The bin clip with `id`, if it is still in the bin. */
  def clipFor(id: String): Option[MediaClip] = bin.find(_.id == id)

  /** Whether any track holds a placed clip — the project has something on the timeline. */
  def hasMedia: Boolean = tracks.exists(_.clips.nonEmpty)

  /** Whether the next imported clip should set the timeline format from its own: only into a fresh
    * project whose spec has not been pinned (by an explicit settings change or an earlier import) and
    * that holds no media yet. This is the auto-adopt gate — a first clip defines the timeline, later
    * clips are conformed to it. */
  def shouldAdoptSpec: Boolean = !specLocked && bin.isEmpty

  /** Set the timeline format explicitly and pin it, so no later import re-adopts. */
  def withSpec(s: TimelineSpec): Project = copy(spec = s, specLocked = true)

  /** The frame just past the furthest clip on any track, or 0 when the timeline is empty. */
  def contentEnd: Int = tracks.map(_.contentEnd).maxOption.getOrElse(0)

  /** The style with `id`, or the first style as a fallback so a dangling reference still renders. */
  def styleFor(id: String): Style = styles.find(_.id == id).getOrElse(styles.head)

  /** The multicam group with `id`, if it is still in the project. */
  def mcFor(id: String): Option[Multicam] = multicams.find(_.id == id)

  /** The lower third (title content) with `id`, if it is still in the project. */
  def titleFor(id: String): Option[LowerThird] = lowerThirds.find(_.id == id)

  /** Replace the track with `id` through `f`, leaving the rest untouched. */
  def updateTrack(id: String)(f: Track => Track): Project =
    copy(tracks = tracks.map(t => if t.id == id then f(t) else t))

  /** The placements that move as a unit with the placement `id`: itself, and — when it is one half of a
    * linked A/V pair — every placement sharing its link id, across tracks. Each is returned with the id
    * of the track it sits on, so a move can respect that track's neighbours. An unlinked clip moves alone. */
  def moveGroupOf(id: String): List[(String, PlacedClip)] =
    val target = tracks.flatMap(t => t.clips.find(_.id == id).map(c => (t.id, c))).headOption
    target match
      case Some((_, pc)) =>
        pc.link match
          case Some(lnk) => tracks.flatMap(t => t.clips.filter(_.link.contains(lnk)).map(c => (t.id, c)))
          case None      => target.toList
      case None => Nil

  /** Write the project to `path` as pretty JSON. */
  def save(path: String): Unit =
    val w = new PrintWriter(new File(path))
    try w.write(this.toJsonPretty)
    finally w.close()

object Project:
  given JsonCodec[Project] = DeriveJsonCodec.gen

  /** The tracks a new project starts with — an empty video and an empty audio lane, always present so
    * the timeline reads as an editor waiting for clips (as in kdenlive) rather than a blank slate. */
  def defaultTracks: List[Track] = List(
    Track("v1", "V1", MediaKind.Video),
    Track("a1", "A1", MediaKind.Audio),
  )

  /** Today's date as an ISO `YYYY-MM-DD` string, the creation date a fresh project is stamped with.
    * Read at the UTC offset — a fixed offset needs no timezone database, so scala-java-time links
    * without the tzdb artifact. */
  def today: String = java.time.LocalDate.now(java.time.ZoneOffset.UTC).toString

  /** A fresh, empty project — no bin, the default empty tracks, no overlays, the preset styles, stamped
    * with today's date. */
  def blank: Project =
    Project("Untitled", Nil, defaultTracks, Nil, Style.presets, created = today)

  /** Read a project from `path`, or a decode error message. */
  def load(path: String): Either[String, Project] =
    val src = Source.fromFile(path)
    try src.mkString.fromJson[Project]
    finally src.close()
