package io.github.edadma.kutter

import java.io.{File, PrintWriter}
import scala.io.Source
import zio.json.*

// The project model — kutter's source of truth, and what a `.kutter` file on disk holds. It is a
// plain data model, deliberately above MLT: `Player.buildGraph` compiles it into a tractor to play
// or export, but the project itself knows nothing of transitions or playlists. That separation is
// what lets a project be created in the UI, generated by a batch script, saved as JSON, and reopened,
// while the graph it compiles to stays an implementation detail.
//
// The model is a fixed-track NLE, like kdenlive: media is *imported into a bin*, then *placed onto
// tracks*. A track is a container — V1, V2 for video (composited top-down) and A1, A2 for audio
// (mixed) — that always exists whether or not it holds anything, and sequences a list of placed clips
// along the timeline. Importing a clip is not the same as putting it on the timeline; a bin clip can
// be placed on several tracks, or several times on one track, each placement its own in/out window.
//
// A lower third is split into the three things that were conflated when it was hardcoded: its
// **content** (the words), its **placement** (when it shows and how it fades), and its **style** (the
// look, chosen from a set of reusable presets rather than baked into the renderer). Lower thirds ride
// on top of the whole track stack — kutter's reason for being is the automated typeset lower thirds.

/** A colour, components in 0..1 — the wire form styles are written in. */
final case class Rgba(r: Double, g: Double, b: Double, a: Double = 1.0)

object Rgba:
  given JsonCodec[Rgba] = DeriveJsonCodec.gen

/** Where a lower third sits along the bottom of the frame; sets the bar's horizontal placement and
  * how its text is aligned within it. */
enum Anchor:
  case LowerLeft, LowerCenter, LowerRight

object Anchor:
  given JsonCodec[Anchor] = DeriveJsonCodec.gen

/** The look of a lower third, independent of its words — a reusable preset the card renderer draws
  * from. A style with a fully transparent `bar` draws no bar (the `shadow` then keeps the text
  * legible over bright footage); `stripe` is the accent edge, absent when `None`.
  *
  * When `texish` is set, the card is typeset from that texish document instead of drawn by the
  * hand-rolled Cairo renderer — the look then lives entirely in the template, and the bar/stripe/colour
  * fields above are ignored. The template reads the overlay's words from the `ltname` and `lttitle`
  * variables (`\the\ltname`, `\the\lttitle`), so one template dresses a whole batch of lower thirds. */
final case class Style(
    id:           String,
    label:        String,
    bar:          Rgba,
    stripe:       Option[Rgba],
    cornerRadius: Double, // as a fraction of the bar's height
    nameColor:    Rgba,
    titleColor:   Rgba,
    nameBold:     Boolean,
    shadow:       Boolean,
    anchor:       Anchor,
    widthFrac:    Double,          // bar width as a fraction of the frame width
    heightFrac:   Double,          // bar height as a fraction of the frame height
    texish:       Option[String] = None, // when set, the card is typeset from this texish document
)

object Style:
  given JsonCodec[Style] = DeriveJsonCodec.gen

  /** The dark translucent bar with a blue accent stripe and a bold name — the broadcast default. */
  val broadcastBlue = Style(
    "broadcast-blue", "Broadcast Blue",
    bar = Rgba(0.05, 0.06, 0.08, 0.72),
    stripe = Some(Rgba(0.29, 0.60, 0.96, 1.0)),
    cornerRadius = 0.12,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.82, 0.86, 0.92, 1),
    nameBold = true,
    shadow = false,
    anchor = Anchor.LowerLeft,
    widthFrac = 0.60,
    heightFrac = 0.18,
  )

  /** A wide solid accent-coloured bar, centred, with white text — a bolder look. */
  val boldBar = Style(
    "bold-bar", "Bold Bar",
    bar = Rgba(0.29, 0.60, 0.96, 0.92),
    stripe = None,
    cornerRadius = 0.06,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.90, 0.94, 1.0, 1),
    nameBold = true,
    shadow = false,
    anchor = Anchor.LowerCenter,
    widthFrac = 0.72,
    heightFrac = 0.16,
  )

  /** No bar at all — white text over a soft shadow, for a clean unobtrusive credit. */
  val minimal = Style(
    "minimal", "Minimal",
    bar = Rgba(0, 0, 0, 0),
    stripe = None,
    cornerRadius = 0.0,
    nameColor = Rgba(1, 1, 1, 1),
    titleColor = Rgba(0.86, 0.89, 0.94, 1),
    nameBold = true,
    shadow = true,
    anchor = Anchor.LowerLeft,
    widthFrac = 0.60,
    heightFrac = 0.18,
  )

  /** A texish-typeset card: the name in bold sans over the title in a lighter weight, set low on the
    * frame with real kerning and no bar. The look is the template, so this is also the worked example
    * of a lower third expressed in texish — copy it into a project and edit the document to taste. */
  val texishCard = minimal.copy(
    id = "texish-card",
    label = "Texish Card",
    texish = Some(texishCardTemplate),
  )

  /** The default card template. It pulls in the `document` macros, makes the text area fill the whole
    * frame (`\geometry margin:0`, so the words can sit right at the bottom edge), drops the page-number
    * footer (a still overlay wants no folio), pushes the words down with `\vfill`, and sets the name and
    * title read from the `ltname`/`lttitle` variables. Numbers are in points, and the card is rendered
    * at one pixel per point, so they read directly against a 1280×720 frame. */
  private def texishCardTemplate: String =
    """\use{document}
      |\geometry margin:0
      |\def footline {}
      |\set leftskip {56}
      |\vfill
      |\noindent{\color{white}\font lmroman 48 {sans bold}\the\ltname}
      |
      |\vskip 8pt
      |
      |\noindent{\color{#c9d4e2}\font lmroman 30 {sans}\the\lttitle}
      |
      |\vskip 64pt
      |""".stripMargin

  /** The styles a new project starts with. */
  val presets: List[Style] = List(broadcastBlue, boldBar, minimal, texishCard)

/** One lower third: its words, its window on the timeline, and the style it wears.
  *
  * `body` is an escape hatch: a raw texish document for this one card, which overrides whatever the
  * style would have drawn (see `CardRenderer`). The words are still available to it as the `ltname` and
  * `lttitle` variables, so a body can read them or ignore them and set the card however it likes. With
  * no `body`, the card is drawn by the style — a texish template when the style has one, else the
  * hand-rolled Cairo look. */
final case class LowerThird(
    id:         String,
    name:       String,
    title:      String,
    inFrame:    Int,
    outFrame:   Int,
    fadeFrames: Int            = 12,
    styleId:    String         = "broadcast-blue",
    body:       Option[String] = None, // a raw texish document for just this card, overriding its style
    source:     Option[String] = None, // the .klt file this was imported from, so a re-import replaces it
):
  /** The fade length, clamped so the in and out fades never overlap. */
  def fade: Int = math.max(1, math.min(fadeFrames, (outFrame - inFrame) / 2))

object LowerThird:
  given JsonCodec[LowerThird] = DeriveJsonCodec.gen

/** Whether a media clip contributes a picture or a sound track. Video clips go on video tracks and are
  * composited top-down; audio clips go on audio tracks and are mixed. */
enum MediaKind:
  case Video, Audio

object MediaKind:
  given JsonCodec[MediaKind] = DeriveJsonCodec.gen

/** One piece of source media in the project's bin: an imported video or audio file. A bin clip is a
  * source, not a placement — it names a file that can be dropped onto a track (once, or several times)
  * with its own in/out window each time. */
final case class MediaClip(id: String, path: String, kind: MediaKind):
  /** The file's basename, for the bin and the clip label. */
  def name: String = path.split('/').lastOption.getOrElse(path)

object MediaClip:
  given JsonCodec[MediaClip] = DeriveJsonCodec.gen

  /** A new bin clip of `kind` for `path`, with a fresh id. */
  def make(path: String, kind: MediaKind): MediaClip =
    MediaClip(s"clip-${System.nanoTime()}", path, kind)

/** A source clip placed on a track: which bin clip it draws from (`clipId`), where it begins on the
  * timeline (`timelineStart`, in frames), and which slice of the source it plays (`inPoint` for
  * `length` frames). Several placements can reference the same bin clip; each carries its own window. */
final case class PlacedClip(
    id:            String,
    clipId:        String,
    timelineStart: Int,
    inPoint:       Int,
    length:        Int,
):
  /** The frame just past this placement's end on the timeline. */
  def timelineEnd: Int = timelineStart + length

object PlacedClip:
  given JsonCodec[PlacedClip] = DeriveJsonCodec.gen

  /** A placement of `clip` at `start`, playing the whole source for `length` frames from its head. */
  def make(clipId: String, start: Int, length: Int, inPoint: Int = 0): PlacedClip =
    PlacedClip(s"pc-${System.nanoTime()}", clipId, start, inPoint, length)

/** A track container: a named lane that always exists and sequences a list of placed clips along the
  * timeline. Video tracks are composited top-down (higher tracks over lower); audio tracks are mixed.
  * `volume` scales the track's sound (`muted` silences it outright), the per-track fader the mixer
  * drives. The clips are kept sorted by their timeline position when the graph is compiled. */
final case class Track(
    id:     String,
    name:   String,
    kind:   MediaKind,
    clips:  List[PlacedClip] = Nil,
    volume: Double           = 1.0,
    muted:  Boolean          = false,
):
  /** The clips in timeline order — the order the graph sequences them in. */
  def ordered: List[PlacedClip] = clips.sortBy(_.timelineStart)

  /** The frame just past the last clip on this track, or 0 when empty. */
  def contentEnd: Int = clips.map(_.timelineEnd).maxOption.getOrElse(0)

  /** The effective linear gain: 0 when muted, else the fader value. */
  def gain: Double = if muted then 0.0 else volume

object Track:
  given JsonCodec[Track] = DeriveJsonCodec.gen

/** A whole project: the bin of imported source media, the tracks the clips are sequenced on, the lower
  * thirds over the whole stack, the styles they draw from, and the master output level. */
final case class Project(
    name:        String,
    bin:         List[MediaClip],
    tracks:      List[Track],
    lowerThirds: List[LowerThird],
    styles:      List[Style],
    master:      Double = 1.0,
):
  /** The video tracks, bottom-to-top — the compositing order (each composited over the ones below). */
  def videoTracks: List[Track] = tracks.filter(_.kind == MediaKind.Video)

  /** The audio tracks — each mixed into the output. */
  def audioTracks: List[Track] = tracks.filter(_.kind == MediaKind.Audio)

  /** The bin clip with `id`, if it is still in the bin. */
  def clipFor(id: String): Option[MediaClip] = bin.find(_.id == id)

  /** Whether any track holds a placed clip — the project has something on the timeline. */
  def hasMedia: Boolean = tracks.exists(_.clips.nonEmpty)

  /** The frame just past the furthest clip on any track, or 0 when the timeline is empty. */
  def contentEnd: Int = tracks.map(_.contentEnd).maxOption.getOrElse(0)

  /** The style with `id`, or the first style as a fallback so a dangling reference still renders. */
  def styleFor(id: String): Style = styles.find(_.id == id).getOrElse(styles.head)

  /** Replace the track with `id` through `f`, leaving the rest untouched. */
  def updateTrack(id: String)(f: Track => Track): Project =
    copy(tracks = tracks.map(t => if t.id == id then f(t) else t))

  /** Write the project to `path` as pretty JSON. */
  def save(path: String): Unit =
    val w = new PrintWriter(new File(path))
    try w.write(this.toJsonPretty)
    finally w.close()

object Project:
  given JsonCodec[Project] = DeriveJsonCodec.gen

  /** The tracks a new project starts with — an empty video and an empty audio lane, always present so
    * the timeline reads as an editor waiting for clips (as in kdenlive) rather than a blank slate. */
  def defaultTracks: List[Track] = List(
    Track("v1", "V1", MediaKind.Video),
    Track("a1", "A1", MediaKind.Audio),
  )

  /** A fresh, empty project — no bin, the default empty tracks, no overlays, the preset styles. */
  def blank: Project =
    Project("Untitled", Nil, defaultTracks, Nil, Style.presets)

  /** Read a project from `path`, or a decode error message. */
  def load(path: String): Either[String, Project] =
    val src = Source.fromFile(path)
    try src.mkString.fromJson[Project]
    finally src.close()
